services:
  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'

#  weather_app:
#    build: ./
#    depends_on:
#      - postgres
#    ports:
#      - '9095:9095'

