spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    instead 'localhost' need 'postgres' if you use docker
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 9095

logging:
  level:
    root: info
